config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  post 'add_tag', to: 'tags#add_tag'
  post 'edit_tag', to: 'tags#edit_tag'
  get 'edit_tag', to: 'tags#edit'
  get 'favourite', to: 'users#favourite'
  resources :images
  resources :tags
  resources :users
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  has_many :users
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  def index
    @images = Image.all
    @users = User.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment = Comment.new
        @image = Image.find(params[:id])
    end

    def create
        @image = Image.find(params[:comment][:image_id])
        @comment = Comment.create(comment_params)
        @comment.save
        @image.comments.append(@comment)
        @image.save
        redirect_to root_path
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to root_path
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
          redirect_to root_path
        else
          render :edit
        end
    end

    private

    def comment_params
      params.require(:comment).permit(:comment, :image_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)
    @image.image.attach(params[:image][:image])
    @image.email = current_user.email
    @image.save
    redirect_to root_path
  end

  def show
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to @image
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to root_path
  end

  def edit
    @image = Image.find(params[:id])
  end

  private
  def image_params
    params.require(:image).permit(:title, :image)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @array = User.all.map { |div| [div.email, div.id] }
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.create(image_params)
    @image.image.attach(params[:image][:image])
    @image.save
    redirect_to root_path
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to @image
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to root_path
  end

  def edit
    @image = Image.find(params[:id])
    @tag = User.find(params[:t_id])
    @array = User.all.map { |div| [div.email, div.id] }
  end

  def add_tag
    @image = Image.find(params[:image_id])
    @image.users.append(User.find(params[:tag_id]))
    @image.save
    redirect_to root_path
  end

  def edit_tag
    @image = Image.find(params[:image_id])
    @image.users.find(params[:old_tag_id]).email = (params[:tag_id])
    @image.save
    redirect_to root_path
  end

  private
  def tag_params
    params.require(:image).permit(:title, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tagged_images = Image.all.map  { |div| if div.users.where(id: current_user.id)
                                                  div
                                                end
                                        }
    @favourites = @user.favourites.map { |id| Image.find(id) }
  end

  def favourite
    if !current_user.favourites.include? (params[:id])
      current_user.favourites.append(params[:id])
      current_user.save
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.slim
= link_to 'My Profile', user_path(current_user.id)
br
- @images.each do |image|
  - if image.image.attached?
    = image_tag image.image
  br
  - if current_user.email == image.email
    = link_to image.title, image
  - else
    = image.title
  br
  - if current_user.email != image.email
    = link_to 'favourite', favourite_path(id: image.id)
  br
  = link_to 'Add tag', new_tag_path(id: image.id)
  br
  |Tags:
  br
  - image.users.each do |tag|
    = tag.email
    | :
    = link_to 'edit', edit_tag_path(id: image.id, t_id: tag.id)
    | :
    = link_to 'destroy', tag_path(:id => tag.id), method: :delete, data: { confirm: "Are you sure?" }, class: "header_delete"
    br
  = link_to 'Add Comment', new_comment_path(id: image.id)
  br
  |Comments:
  br
  - image.comments.each do |comment|
    =comment.comment
    = link_to 'Edit', edit_comment_path(id: comment.id)
    | :
    = link_to 'destroy', comment_path(:id => comment.id), method: :delete, data: { confirm: "Are you sure?" }, class: "header_delete"
    br
br
= link_to "upload an image", new_image_path

app/views/comments/edit.html.slim
=form_with model: @comment do |form|
    =form.label :comment
    =form.text_field :comment
    =form.submit

app/views/comments/new.html.slim
=form_with model: @comment do |form|
    =form.label :comment
    =form.text_field :comment
    =form.hidden_field(:image_id, :value => @image.id)
    =form.submit

app/views/images/edit.html.slim
= form_with model: @image do |form|
  = form.label :title
  = form.text_field :title
  br
  = form.file_field :image
  br
  =form.submit

app/views/images/new.html.slim
= form_with model: @image do |form|
  = form.label :title
  = form.text_field :title
  br
  = form.file_field :image
  br
  =form.submit

app/views/images/show.html.slim
- if @image.image.attached?
= image_tag @image.image
br
= @image.title
br
= link_to 'edit', edit_image_path
br
  = link_to "Destroy", image_path(:iamge_id => @image.id), method: :delete, data: { confirm: "Are you sure?" }, class: "header_delete"
br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveRecordProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tags/edit.html.slim
= form_with  url: "/edit_tag", method: :post do |form|
  = form.hidden_field(:image_id, :value => @image.id)
  = form.hidden_field(:old_tag_id, :value => @tag.id)
  = form.label :add_tag
  = form.select :tag_id, @array
  = form.submit

app/views/tags/new.html.slim
= form_with  url: "/add_tag", method: :post do |form|
  = form.hidden_field(:image_id, :value => @image.id)
  = form.label :add_tag
  = form.select :tag_id, @array
  = form.submit

app/views/users/show.html.slim
= @user.email
br
|tagged pictures:
br
- @tagged_images.each do |image|
  - if image.image.attached?
    = image_tag image.image
br
|favourite pictures:
br
- @favourites.each do |favourite|
  - if favourite.image.attached?
    = image_tag favourite.image